name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  # 自动格式化代码并提交
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format code with deno fmt
        run: deno fmt

      - name: Commit and push changes if there are any
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if ! git diff --cached --exit-code; then
            git commit -m "Auto-format code"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 编译并发布文件
  compile:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Compile for Linux
        run: deno compile --target x86_64-unknown-linux-gnu -o ./dist/auto-class-linux -A ./main.ts

      - name: Compile for macOS
        run: deno compile --target x86_64-apple-darwin -o ./dist/auto-class-macos -A ./main.ts

      - name: Compile for Windows
        run: deno compile --target x86_64-pc-windows-msvc -o ./dist/auto-class-windows.exe -A ./main.ts

      - name: Create a Git tag
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')  # 可根据需要调整版本号格式
          git tag "v$VERSION"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
